# Generated by Django 4.2.29 on 2026-04-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_logistics_tracking_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logisticsratecard',
            new_name='core_logist_carrier_a3ffd5_idx',
            old_name='core_logist_carrier_4b834f_idx',
        ),
        migrations.RenameIndex(
            model_name='logisticstrackingevent',
            new_name='core_logist_shipmen_a1cd84_idx',
            old_name='core_logist_shipment_4c2c9f_idx',
        ),
        migrations.RenameIndex(
            model_name='platformorder',
            new_name='core_platfo_order_i_e34bc2_idx',
            old_name='core_platfo_order_i_a09be5_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='core_produc_platfor_988f42_idx',
            old_name='core_produc_platfor_70041e_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='core_produc_platfor_2c70ff_idx',
            old_name='core_produc_platfor_80f80f_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='core_produc_product_ee7f58_idx',
            old_name='core_produc_product_434761_idx',
        ),
        migrations.RenameIndex(
            model_name='userphonebinding',
            new_name='core_userph_country_ba86e2_idx',
            old_name='core_userph_country_f7f9f5_idx',
        ),
    ]
