from django.urls import path

from .views import (
    AuthCallbackView,
    CaptchaChallengeView,
    AuthLoginView,
    DemoAuthLoginView,
    DemoAuthMeView,
    DemoAuthRefreshView,
    DemoAuthRegisterView,
    AuthRefreshView,
    MobileAuthLoginView,
    UserAccountDeleteView,
    PhoneRebindAppealCreateView,
    SmsChannelStatsView,
    CollectionTaskCreateView,
    CollectionTaskStatusView,
    DeadLetterListView,
    DeadLetterReplayView,
    GoodsDetailView,
    GoodsListCreateView,
    GoodsListingSyncView,
    GoodsBatchListingSyncView,
    HealthCheckView,
    InventoryAlertsView,
    InventoryLogsView,
    InventorySyncView,
    InventoryOverviewView,
    InventoryAdjustView,
    WarehousesView,
    WarehouseDetailView,
    LogisticsShipmentsView,
    LogisticsTrackView,
    LogisticsWebhookView,
    FreightEstimateView,
    LogisticsCarriersView,
    LogisticsSyncView,
    LogisticsSubscribeView,
    OrdersExportView,
    OrdersListView,
    OrdersStatsView,
    OrderAddressUpdateView,
    OrderStatusUpdateView,
    OrderDetailView,
    OrderConfirmView,
    OrderShipView,
    OrderCancelView,
    OrderRemarkView,
    OpsWhoAmIView,
    ReplayAuditLogListView,
    AuthMeView,
    ShopListView,
    ShopUnbindView,
    SmsCodeSendView,
    SmsCodeVerifyView,
    SyncLogView,
    SyncTriggerView,
    DemoGoodsListView,
    DemoGoodsDetailView,
    DemoAuthSendSmsView,
    DemoAuthVerifySmsView,
    DemoSmsQueryView,
    CollectAuthView,
    CollectTaskView,
    AiExtendedView,
    DemoOrdersView,
    DemoOrdersStatsView,
    DemoInventoryView,
    DemoLogisticsView,
    Collect1688SingleView,
    Collect1688BatchView,
    AiProxyView,
    AiGenerateTitleView,
    AiGenerateDescriptionView,
    AiGenerateFeaturesView,
    UserLoginView,
    UserRegisterView,
    UserTokenRefreshView,
    DashboardStatsView,
    DashboardRecentOrdersView,
    DashboardSalesTrendView,
    DashboardNewOrdersSinceView,
    ReportsSummaryView,
    ImageUploadView,
)

_common_urls = [
    path("auth/captcha/challenge", CaptchaChallengeView.as_view(), name="auth-captcha-challenge"),
    path("auth/sms/send-code", SmsCodeSendView.as_view(), name="auth-sms-send-code"),
    path("auth/sms/verify-code", SmsCodeVerifyView.as_view(), name="auth-sms-verify-code"),
    path("auth/mobile/login", MobileAuthLoginView.as_view(), name="auth-mobile-login"),
    path("user/account/", UserAccountDeleteView.as_view(), name="user-account-delete"),
    path("user/phone-rebind-appeals", PhoneRebindAppealCreateView.as_view(), name="user-phone-rebind-appeals"),
    path("ops/sms/channel-stats", SmsChannelStatsView.as_view(), name="ops-sms-channel-stats"),
    path("auth/<str:platform>/login/", AuthLoginView.as_view(), name="auth-login"),
    path("auth/<str:platform>/callback/", AuthCallbackView.as_view(), name="auth-callback"),
    path("auth/<str:platform>/refresh/", AuthRefreshView.as_view(), name="auth-refresh"),
    path("goods/", GoodsListCreateView.as_view(), name="goods-list-create"),
    path("goods/<int:goods_id>", GoodsDetailView.as_view(), name="goods-detail"),
    path("shops/", ShopListView.as_view(), name="shops-list"),
    path("shops/unbind/", ShopUnbindView.as_view(), name="shops-unbind"),
    path("inventory/alerts", InventoryAlertsView.as_view(), name="inventory-alerts"),
    path("inventory/logs", InventoryLogsView.as_view(), name="inventory-logs"),
    path("inventory/sync", InventorySyncView.as_view(), name="inventory-sync"),
    path("inventory/overview", InventoryOverviewView.as_view(), name="inventory-overview"),
    path("inventory/adjust", InventoryAdjustView.as_view(), name="inventory-adjust"),
    path("warehouses/", WarehousesView.as_view(), name="warehouses-list"),
    path("warehouses/<int:warehouse_id>/", WarehouseDetailView.as_view(), name="warehouse-detail"),
    path("orders/", OrdersListView.as_view(), name="orders-list"),
    path("orders/status-counts/", OrdersStatsView.as_view(), name="orders-stats"),
    path("orders/<int:order_id>/", OrderDetailView.as_view(), name="order-detail"),
    path("orders/<int:order_id>/address", OrderAddressUpdateView.as_view(), name="orders-address-update"),
    path("orders/<int:order_id>/status", OrderStatusUpdateView.as_view(), name="orders-status-update"),
    path("orders/<int:order_id>/confirm/", OrderConfirmView.as_view(), name="order-confirm"),
    path("orders/<int:order_id>/ship/", OrderShipView.as_view(), name="order-ship"),
    path("orders/<int:order_id>/cancel/", OrderCancelView.as_view(), name="order-cancel"),
    path("orders/<int:order_id>/remark/", OrderRemarkView.as_view(), name="order-remark"),
    path("orders/export", OrdersExportView.as_view(), name="orders-export"),
    path("logistics/shipments/", LogisticsShipmentsView.as_view(), name="logistics-shipments"),
    path("logistics/track/<str:waybill>", LogisticsTrackView.as_view(), name="logistics-track"),
    path("logistics/webhook", LogisticsWebhookView.as_view(), name="logistics-webhook"),
    path("logistics/freight-estimate", FreightEstimateView.as_view(), name="logistics-freight-estimate"),
    path("logistics/carriers/", LogisticsCarriersView.as_view(), name="logistics-carriers"),
    path("logistics/sync/", LogisticsSyncView.as_view(), name="logistics-sync"),
    path("logistics/subscribe/", LogisticsSubscribeView.as_view(), name="logistics-subscribe"),
    path("tasks/collect/", CollectionTaskCreateView.as_view(), name="task-collect"),
    path("tasks/<int:task_id>/status/", CollectionTaskStatusView.as_view(), name="task-status"),
    path("sync/trigger/", SyncTriggerView.as_view(), name="sync-trigger"),
    path("sync/log/", SyncLogView.as_view(), name="sync-log"),
    path("ops/dead-letter/", DeadLetterListView.as_view(), name="dead-letter-list"),
    path("ops/dead-letter/<int:dead_letter_id>/replay/", DeadLetterReplayView.as_view(), name="dead-letter-replay"),
    path("ops/replay-audit/", ReplayAuditLogListView.as_view(), name="replay-audit-list"),
    path("ops/whoami/", OpsWhoAmIView.as_view(), name="ops-whoami"),
    path("health/", HealthCheckView.as_view(), name="health-check"),
    path("dashboard/stats", DashboardStatsView.as_view(), name="dashboard-stats"),
    path("dashboard/recent-orders", DashboardRecentOrdersView.as_view(), name="dashboard-recent-orders"),
    path("dashboard/sales-trend", DashboardSalesTrendView.as_view(), name="dashboard-sales-trend"),
    path("dashboard/new-orders-since", DashboardNewOrdersSinceView.as_view(), name="dashboard-new-orders-since"),
    path("reports/summary/", ReportsSummaryView.as_view(), name="reports-summary"),
]

_demo_urls = [
    path("auth/login", UserLoginView.as_view(), name="demo-auth-login"),
    path("auth/me", AuthMeView.as_view(), name="demo-auth-me"),
    path("auth/refresh", UserTokenRefreshView.as_view(), name="demo-auth-refresh"),
    path("auth/register", UserRegisterView.as_view(), name="demo-auth-register"),
    path("auth/register/", UserRegisterView.as_view(), name="demo-auth-register-slash"),
    path("auth/send-sms", SmsCodeSendView.as_view(), name="demo-auth-send-sms"),
    path("auth/verify-sms", SmsCodeVerifyView.as_view(), name="demo-auth-verify-sms"),
    path("sms/send/", SmsCodeSendView.as_view(), name="demo-sms-send"),
    path("sms/verify/", SmsCodeVerifyView.as_view(), name="demo-sms-verify"),
    path("sms/query/", SmsCodeSendView.as_view(), name="demo-sms-query"),
    path("sms/send-batch/", SmsCodeSendView.as_view(), name="demo-sms-send-batch"),
    path("v1/goods/list", GoodsListCreateView.as_view(), name="demo-goods-list"),
    path("v1/goods/detail/<int:goods_id>/", GoodsDetailView.as_view(), name="demo-goods-detail"),
    path("v1/products/", GoodsListCreateView.as_view(), name="demo-products-list"),
    path("v1/orders/", OrdersListView.as_view(), name="demo-orders-list"),
    path("v1/orders/stats/", OrdersStatsView.as_view(), name="demo-orders-stats"),
    path("v1/orders/<int:order_id>/", OrderDetailView.as_view(), name="demo-orders-detail"),
    path("v1/orders/<int:order_id>/confirm/", OrderConfirmView.as_view(), name="demo-orders-confirm"),
    path("v1/orders/<int:order_id>/ship/", OrderShipView.as_view(), name="demo-orders-ship"),
    path("v1/orders/<int:order_id>/cancel/", OrderCancelView.as_view(), name="demo-orders-cancel"),
    path("v1/orders/<int:order_id>/remark/", OrderRemarkView.as_view(), name="demo-orders-remark"),
    path("v1/collect/<str:platform>/auth/login/", CollectAuthView.as_view(), name="demo-collect-auth-login"),
    path("v1/collect/<str:platform>/auth/callback/", CollectAuthView.as_view(), name="demo-collect-auth-callback"),
    path("v1/collect/<str:platform>/auth/status/", CollectAuthView.as_view(), name="demo-collect-auth-status"),
    path("v1/collect/<str:platform>/auth/logout/", CollectAuthView.as_view(), name="demo-collect-auth-logout"),
    path("v1/inventory/list/", GoodsListCreateView.as_view(), name="demo-inventory-list"),
    path("v1/inventory/alerts/", InventoryAlertsView.as_view(), name="demo-inventory-alerts"),
    path("v1/inventory/sku/<str:sku>/", GoodsDetailView.as_view(), name="demo-inventory-sku"),
    path("v1/inventory/adjust/", InventoryAdjustView.as_view(), name="demo-inventory-adjust"),
    path("v1/inventory/logs/", InventoryLogsView.as_view(), name="demo-inventory-logs"),
    path("v1/inventory/overview/", InventoryOverviewView.as_view(), name="demo-inventory-overview"),
    path("v1/inventory/warehouses/", WarehousesView.as_view(), name="demo-inventory-warehouses"),
    path("v1/inventory/sync/trigger/", InventorySyncView.as_view(), name="demo-inventory-sync-trigger"),
    path("v1/inventory/sync/log/", InventoryLogsView.as_view(), name="demo-inventory-sync-log"),
    path("v1/logistics/shipments/", LogisticsShipmentsView.as_view(), name="demo-logistics-shipments"),
    path("v1/logistics/stats/", OrdersStatsView.as_view(), name="demo-logistics-stats"),
    path("v1/logistics/track/<str:waybill>/", LogisticsTrackView.as_view(), name="demo-logistics-track"),
    path("v1/logistics/sync/", LogisticsSyncView.as_view(), name="demo-logistics-sync"),
    path("v1/logistics/carriers/", LogisticsCarriersView.as_view(), name="demo-logistics-carriers"),
    path("v1/logistics/subscribe/", LogisticsSubscribeView.as_view(), name="demo-logistics-subscribe"),
    path("ai/proxy", AiProxyView.as_view(), name="ai-proxy"),
    path("ai/generate-title/", AiGenerateTitleView.as_view(), name="demo-ai-generate-title"),
    path("ai/generate-description/", AiGenerateDescriptionView.as_view(), name="demo-ai-generate-description"),
    path("ai/generate-features/", AiGenerateFeaturesView.as_view(), name="demo-ai-generate-features"),
    path("ai/chat/", AiExtendedView.as_view(), name="demo-ai-chat"),
    path("ai/image/generate/", AiExtendedView.as_view(), name="demo-ai-image-generate"),
    path("ai/image/edit/", AiExtendedView.as_view(), name="demo-ai-image-edit"),
    path("ai/translate/", AiExtendedView.as_view(), name="demo-ai-translate"),
    path("ai/refine-description/", AiExtendedView.as_view(), name="demo-ai-refine-description"),
]

_v1_real_urls = [
    path("v1/goods/list", GoodsListCreateView.as_view(), name="v1-goods-list"),
    path("v1/goods/detail/<int:goods_id>/", GoodsDetailView.as_view(), name="v1-goods-detail"),
    path("v1/products/", GoodsListCreateView.as_view(), name="v1-products-list"),
    path("v1/goods/listing/", GoodsListingSyncView.as_view(), name="v1-goods-listing-sync"),
    path("v1/goods/listing/batch/", GoodsBatchListingSyncView.as_view(), name="v1-goods-listing-batch-sync"),
    path("v1/collect/1688/single/", Collect1688SingleView.as_view(), name="v1-collect-1688-single"),
    path("v1/collect/1688/batch/", Collect1688BatchView.as_view(), name="v1-collect-1688-batch"),
    path("v1/collect/task/", CollectTaskView.as_view(), name="v1-collect-task-create"),
    path("v1/collect/task/list/", CollectTaskView.as_view(), name="v1-collect-task-list"),
    path("v1/collect/task/<int:task_id>/", CollectTaskView.as_view(), name="v1-collect-task-detail"),
    path("v1/collect/task/<int:task_id>/status/", CollectTaskView.as_view(), name="v1-collect-task-status"),
    path("v1/collect/task/<int:task_id>/cancel/", CollectTaskView.as_view(), name="v1-collect-task-cancel"),
    path("v1/orders/", OrdersListView.as_view(), name="v1-orders-list"),
    path("v1/orders/stats/", OrdersStatsView.as_view(), name="v1-orders-stats"),
    path("v1/orders/<int:order_id>/", OrderDetailView.as_view(), name="v1-orders-detail"),
    path("v1/orders/<int:order_id>/confirm/", OrderConfirmView.as_view(), name="v1-orders-confirm"),
    path("v1/orders/<int:order_id>/ship/", OrderShipView.as_view(), name="v1-orders-ship"),
    path("v1/orders/<int:order_id>/cancel/", OrderCancelView.as_view(), name="v1-orders-cancel"),
    path("v1/orders/<int:order_id>/remark/", OrderRemarkView.as_view(), name="v1-orders-remark"),
    path("v1/upload/image/", ImageUploadView.as_view(), name="v1-upload-image"),
]

_business_auth_urls = [
    path("auth/register", UserRegisterView.as_view(), name="auth-register"),
    path("auth/register/", UserRegisterView.as_view(), name="auth-register-slash"),
    path("auth/login", UserLoginView.as_view(), name="auth-login-user"),
    path("auth/refresh", UserTokenRefreshView.as_view(), name="auth-refresh-user"),
    path("auth/me", AuthMeView.as_view(), name="auth-me"),
    path("auth/send-sms", SmsCodeSendView.as_view(), name="auth-send-sms-compat"),
    path("auth/verify-sms", SmsCodeVerifyView.as_view(), name="auth-verify-sms-compat"),
]

urlpatterns = (_business_auth_urls + _v1_real_urls + _common_urls + _demo_urls)

