from django.urls import path

from .views import (
    AuthCallbackView,
    AuthLoginView,
    AuthMeView,
    AuthRefreshView,
    CollectionTaskCreateView,
    CollectionTaskStatusView,
    DeadLetterListView,
    DeadLetterReplayView,
    GoodsDetailView,
    GoodsListCreateView,
    HealthCheckView,
    InventoryAlertsView,
    InventoryLogsView,
    InventorySyncView,
    LogisticsShipmentsView,
    LogisticsTrackView,
    OrdersExportView,
    OrdersListView,
    OrderStatusUpdateView,
    OpsWhoAmIView,
    ReplayAuditLogListView,
    ShopListView,
    SyncLogView,
    SyncTriggerView,
)

urlpatterns = [
    path("auth/me", AuthMeView.as_view(), name="auth-me"),
    path("auth/<str:platform>/login/", AuthLoginView.as_view(), name="auth-login"),
    path("auth/<str:platform>/callback/", AuthCallbackView.as_view(), name="auth-callback"),
    path("auth/<str:platform>/refresh/", AuthRefreshView.as_view(), name="auth-refresh"),
    path("goods/", GoodsListCreateView.as_view(), name="goods-list-create"),
    path("goods/<int:goods_id>", GoodsDetailView.as_view(), name="goods-detail"),
    path("shops/", ShopListView.as_view(), name="shops-list"),
    path("inventory/alerts", InventoryAlertsView.as_view(), name="inventory-alerts"),
    path("inventory/logs", InventoryLogsView.as_view(), name="inventory-logs"),
    path("inventory/sync", InventorySyncView.as_view(), name="inventory-sync"),
    path("orders/", OrdersListView.as_view(), name="orders-list"),
    path("orders/<int:order_id>/status", OrderStatusUpdateView.as_view(), name="orders-status-update"),
    path("orders/export", OrdersExportView.as_view(), name="orders-export"),
    path("logistics/shipments/", LogisticsShipmentsView.as_view(), name="logistics-shipments"),
    path("logistics/track/<str:waybill>", LogisticsTrackView.as_view(), name="logistics-track"),
    path("tasks/collect/", CollectionTaskCreateView.as_view(), name="task-collect"),
    path("tasks/<int:task_id>/status/", CollectionTaskStatusView.as_view(), name="task-status"),
    path("sync/trigger/", SyncTriggerView.as_view(), name="sync-trigger"),
    path("sync/log/", SyncLogView.as_view(), name="sync-log"),
    path("ops/dead-letter/", DeadLetterListView.as_view(), name="dead-letter-list"),
    path("ops/dead-letter/<int:dead_letter_id>/replay/", DeadLetterReplayView.as_view(), name="dead-letter-replay"),
    path("ops/replay-audit/", ReplayAuditLogListView.as_view(), name="replay-audit-list"),
    path("ops/whoami/", OpsWhoAmIView.as_view(), name="ops-whoami"),
    path("health/", HealthCheckView.as_view(), name="health-check"),
]
