from django.urls import path

from .views import (
    AuthCallbackView,
    CaptchaChallengeView,
    AuthLoginView,
    DemoAuthLoginView,
    DemoAuthMeView,
    DemoAuthRefreshView,
    DemoAuthRegisterView,
    AuthRefreshView,
    MobileAuthLoginView,
    UserAccountDeleteView,
    PhoneRebindAppealCreateView,
    SmsChannelStatsView,
    CollectionTaskCreateView,
    CollectionTaskStatusView,
    DeadLetterListView,
    DeadLetterReplayView,
    GoodsDetailView,
    GoodsListCreateView,
    HealthCheckView,
    InventoryAlertsView,
    InventoryLogsView,
    InventorySyncView,
    LogisticsShipmentsView,
    LogisticsTrackView,
    LogisticsWebhookView,
    FreightEstimateView,
    OrdersExportView,
    OrdersListView,
    OrderAddressUpdateView,
    OrderStatusUpdateView,
    OpsWhoAmIView,
    ReplayAuditLogListView,
    ShopListView,
    SmsCodeSendView,
    SmsCodeVerifyView,
    SyncLogView,
    SyncTriggerView,
    DemoGoodsListView,
    DemoGoodsDetailView,
    DemoGoodsListingSyncView,
    DemoGoodsBatchListingSyncView,
    DemoAuthSendSmsView,
    DemoAuthVerifySmsView,
    DemoSmsQueryView,
    DemoCollectAuthView,
    DemoCollectTaskView,
    DemoAiExtendedView,
    DemoOrdersView,
    DemoOrdersStatsView,
    DemoInventoryView,
    DemoLogisticsView,
    DemoCollect1688SingleView,
    DemoCollect1688BatchView,
    AiProxyView,
    DemoAiGenerateTitleView,
    DemoAiGenerateDescriptionView,
    DemoAiGenerateFeaturesView,
)

urlpatterns = [
    # 演示最高优先级：严格匹配前端固定路径，全部直通返回 200
    path("auth/login", DemoAuthLoginView.as_view(), name="demo-auth-login"),
    path("auth/me", DemoAuthMeView.as_view(), name="demo-auth-me"),
    path("auth/refresh", DemoAuthRefreshView.as_view(), name="demo-auth-refresh"),
    path("auth/register", DemoAuthRegisterView.as_view(), name="demo-auth-register"),
    path("auth/register/", DemoAuthRegisterView.as_view(), name="demo-auth-register-slash"),
    path("auth/send-sms", DemoAuthSendSmsView.as_view(), name="demo-auth-send-sms"),
    path("auth/verify-sms", DemoAuthVerifySmsView.as_view(), name="demo-auth-verify-sms"),
    path("sms/send/", DemoAuthSendSmsView.as_view(), name="demo-sms-send"),
    path("sms/verify/", DemoAuthVerifySmsView.as_view(), name="demo-sms-verify"),
    path("sms/query/", DemoSmsQueryView.as_view(), name="demo-sms-query"),
    path("sms/send-batch/", DemoAuthSendSmsView.as_view(), name="demo-sms-send-batch"),
    path("auth/captcha/challenge", CaptchaChallengeView.as_view(), name="auth-captcha-challenge"),
    path("auth/sms/send-code", SmsCodeSendView.as_view(), name="auth-sms-send-code"),
    path("auth/sms/verify-code", SmsCodeVerifyView.as_view(), name="auth-sms-verify-code"),
    path("auth/mobile/login", MobileAuthLoginView.as_view(), name="auth-mobile-login"),
    path("user/account/", UserAccountDeleteView.as_view(), name="user-account-delete"),
    path("user/phone-rebind-appeals", PhoneRebindAppealCreateView.as_view(), name="user-phone-rebind-appeals"),
    path("ops/sms/channel-stats", SmsChannelStatsView.as_view(), name="ops-sms-channel-stats"),
    path("auth/<str:platform>/login/", AuthLoginView.as_view(), name="auth-login"),
    path("auth/<str:platform>/callback/", AuthCallbackView.as_view(), name="auth-callback"),
    path("auth/<str:platform>/refresh/", AuthRefreshView.as_view(), name="auth-refresh"),
    path("goods/", GoodsListCreateView.as_view(), name="goods-list-create"),
    path("goods/<int:goods_id>", GoodsDetailView.as_view(), name="goods-detail"),
    # 演示：对齐 /api/v1/goods/list 与 /api/v1/goods/listing/
    path("v1/goods/list", DemoGoodsListView.as_view(), name="demo-goods-list"),
    path("v1/goods/detail/<int:goods_id>/", DemoGoodsDetailView.as_view(), name="demo-goods-detail"),
    path("v1/products/", DemoGoodsListView.as_view(), name="demo-products-list"),
    path("v1/goods/listing/", DemoGoodsListingSyncView.as_view(), name="demo-goods-listing-sync"),
    path("v1/goods/listing/batch/", DemoGoodsBatchListingSyncView.as_view(), name="demo-goods-listing-batch-sync"),
    path("v1/orders/", DemoOrdersView.as_view(), name="demo-orders-list"),
    path("v1/orders/stats/", DemoOrdersStatsView.as_view(), name="demo-orders-stats"),
    path("v1/orders/<int:order_id>/", DemoOrdersView.as_view(), name="demo-orders-detail"),
    path("v1/orders/<int:order_id>/<str:action>/", DemoOrdersView.as_view(), name="demo-orders-action"),
    path("v1/collect/1688/single/", DemoCollect1688SingleView.as_view(), name="demo-collect-1688-single"),
    path("v1/collect/1688/batch/", DemoCollect1688BatchView.as_view(), name="demo-collect-1688-batch"),
    path("v1/collect/<str:platform>/auth/login/", DemoCollectAuthView.as_view(), name="demo-collect-auth-login"),
    path("v1/collect/<str:platform>/auth/callback/", DemoCollectAuthView.as_view(), name="demo-collect-auth-callback"),
    path("v1/collect/<str:platform>/auth/status/", DemoCollectAuthView.as_view(), name="demo-collect-auth-status"),
    path("v1/collect/<str:platform>/auth/logout/", DemoCollectAuthView.as_view(), name="demo-collect-auth-logout"),
    path("v1/collect/task/", DemoCollectTaskView.as_view(), name="demo-collect-task-create"),
    path("v1/collect/task/list/", DemoCollectTaskView.as_view(), name="demo-collect-task-list"),
    path("v1/collect/task/<int:task_id>/", DemoCollectTaskView.as_view(), name="demo-collect-task-detail"),
    path("v1/collect/task/<int:task_id>/status/", DemoCollectTaskView.as_view(), name="demo-collect-task-status"),
    path("v1/collect/task/<int:task_id>/cancel/", DemoCollectTaskView.as_view(), name="demo-collect-task-cancel"),
    path("v1/inventory/list/", DemoInventoryView.as_view(), name="demo-inventory-list"),
    path("v1/inventory/alerts/", DemoInventoryView.as_view(), name="demo-inventory-alerts"),
    path("v1/inventory/sku/<str:sku>/", DemoInventoryView.as_view(), name="demo-inventory-sku"),
    path("v1/inventory/adjust/", DemoInventoryView.as_view(), name="demo-inventory-adjust"),
    path("v1/inventory/logs/", DemoInventoryView.as_view(), name="demo-inventory-logs"),
    path("v1/inventory/overview/", DemoInventoryView.as_view(), name="demo-inventory-overview"),
    path("v1/inventory/warehouses/", DemoInventoryView.as_view(), name="demo-inventory-warehouses"),
    path("v1/inventory/sync/trigger/", DemoInventoryView.as_view(), name="demo-inventory-sync-trigger"),
    path("v1/inventory/sync/log/", DemoInventoryView.as_view(), name="demo-inventory-sync-log"),
    path("v1/logistics/shipments/", DemoLogisticsView.as_view(), name="demo-logistics-shipments"),
    path("v1/logistics/stats/", DemoLogisticsView.as_view(), name="demo-logistics-stats"),
    path("v1/logistics/track/<str:waybill>/", DemoLogisticsView.as_view(), name="demo-logistics-track"),
    path("v1/logistics/sync/", DemoLogisticsView.as_view(), name="demo-logistics-sync"),
    path("v1/logistics/carriers/", DemoLogisticsView.as_view(), name="demo-logistics-carriers"),
    path("v1/logistics/subscribe/", DemoLogisticsView.as_view(), name="demo-logistics-subscribe"),
    # 演示：AI 中枢转发代理（路径固定在 /api/ai/proxy）
    path("ai/proxy", AiProxyView.as_view(), name="ai-proxy"),
    path("ai/generate-title/", DemoAiGenerateTitleView.as_view(), name="demo-ai-generate-title"),
    path("ai/generate-description/", DemoAiGenerateDescriptionView.as_view(), name="demo-ai-generate-description"),
    path("ai/generate-features/", DemoAiGenerateFeaturesView.as_view(), name="demo-ai-generate-features"),
    path("ai/chat/", DemoAiExtendedView.as_view(), name="demo-ai-chat"),
    path("ai/image/generate/", DemoAiExtendedView.as_view(), name="demo-ai-image-generate"),
    path("ai/image/edit/", DemoAiExtendedView.as_view(), name="demo-ai-image-edit"),
    path("ai/translate/", DemoAiExtendedView.as_view(), name="demo-ai-translate"),
    path("ai/refine-description/", DemoAiExtendedView.as_view(), name="demo-ai-refine-description"),
    path("shops/", ShopListView.as_view(), name="shops-list"),
    path("inventory/alerts", InventoryAlertsView.as_view(), name="inventory-alerts"),
    path("inventory/logs", InventoryLogsView.as_view(), name="inventory-logs"),
    path("inventory/sync", InventorySyncView.as_view(), name="inventory-sync"),
    path("orders/", OrdersListView.as_view(), name="orders-list"),
    path("orders/<int:order_id>/address", OrderAddressUpdateView.as_view(), name="orders-address-update"),
    path("orders/<int:order_id>/status", OrderStatusUpdateView.as_view(), name="orders-status-update"),
    path("orders/export", OrdersExportView.as_view(), name="orders-export"),
    path("logistics/shipments/", LogisticsShipmentsView.as_view(), name="logistics-shipments"),
    path("logistics/track/<str:waybill>", LogisticsTrackView.as_view(), name="logistics-track"),
    path("logistics/webhook", LogisticsWebhookView.as_view(), name="logistics-webhook"),
    path("logistics/freight-estimate", FreightEstimateView.as_view(), name="logistics-freight-estimate"),
    path("tasks/collect/", CollectionTaskCreateView.as_view(), name="task-collect"),
    path("tasks/<int:task_id>/status/", CollectionTaskStatusView.as_view(), name="task-status"),
    path("sync/trigger/", SyncTriggerView.as_view(), name="sync-trigger"),
    path("sync/log/", SyncLogView.as_view(), name="sync-log"),
    path("ops/dead-letter/", DeadLetterListView.as_view(), name="dead-letter-list"),
    path("ops/dead-letter/<int:dead_letter_id>/replay/", DeadLetterReplayView.as_view(), name="dead-letter-replay"),
    path("ops/replay-audit/", ReplayAuditLogListView.as_view(), name="replay-audit-list"),
    path("ops/whoami/", OpsWhoAmIView.as_view(), name="ops-whoami"),
    path("health/", HealthCheckView.as_view(), name="health-check"),
]
