"""选品引擎 API 业务错误码（与 HTTP status 配合使用）。"""

ROAS_DENOMINATOR_ZERO = "ROAS_DENOMINATOR_ZERO"
ROAS_INVALID_INPUT = "ROAS_INVALID_INPUT"
PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
WMS_FREIGHT_FAILED = "WMS_FREIGHT_FAILED"
